### ISSUE TITLE
Unable to align warnings on Nextalign

### ISSUE THREAD

**Issue by andersonbrito** [nextstrain/nextclade#356] opened 2021-02-19 02:13 UTC
Hey, thank you for developing Nextalign. :)

I'm testing `nextalign` using some of the sequences listed as reference genomes by pangoLEARN (all 'passed_qc'). Since many of them were flagged as 'Unable to align', and excluded from the final results, I was wondering if there is a way to make sure all genomes are kept in the final alignment, regardless of insertions, deletions, etc.

> Warning: in sequence "England/20132079304/2020": Unable to align: too many insertions, deletions, duplications, or ambiguous seed matches. Note that this sequence will be excluded from results.

Thank you

**Comment by ivan-aksamentov** [comment] 2021-02-19 06:07
Hi Anderson @andersonbrito,

Thanks for reporting that!

> make sure all genomes are kept in the final alignment

I am not sure what it would look like. The "Unable to align" message means that the seed matching has failed and that the alignment algorithm was not able to run. That is, there is no alignment to output. Would you expect to find unaligned sequences to copied over from input file to the output file?

You might try to to tweak some of the parameters (see `nextalign --help`), such as number of seeds, seed length, spacing, number of mismatches, various scores etc., and see if that helps and makes sense for your particular situation.

I am going to try and run with the pangoLearn data and see what's happening there.

**Comment by ivan-aksamentov** [comment] 2021-02-19 09:59
I downloaded `England/20132079304/2020` (EPI_ISL_423802) from GISAID but cannot reproduce the warning. It aligns successfully for me.

Could you please tell me what version of Nextalign are you running? (`nextalign --version`)

Could not find a quick way of downloading the pangoLearn data. Could you point me to it? Alternatively, please provide EPI ISLs of relevant sequences, so that  could download them and investigate the warnings.

**Comment by rneher** [comment] 2021-02-19 11:22
This genomes lacks the `N` gene. So if you translate `N` it will complain about that, but yes. But there are cases where the seed matching should work but doesn't. I'll look into that.

**Comment by andersonbrito** [comment] 2021-02-19 13:15
Hi @ivan-aksamentov and @rneher,

Thank you for your quick replies. The list of genomes I'm referring to can be found here: https://raw.githubusercontent.com/cov-lineages/pangoLEARN/master/pangoLEARN/data/lineages.metadata.csv

I've selected one representative genome per PANGO lineage, 876 in total (see list [here](https://www.dropbox.com/s/y4rvbwgnricqikq/pango_genomes.txt?dl=0)). Among those, 121 got excluded. You can see all the warnings in [this file](https://www.dropbox.com/s/gw0128nnmqj0mn0/warnings.txt?dl=0), and you can find a list of genomes that were excluded [here](https://www.dropbox.com/s/iudzvjsb4mt6jq9/excluded.txt?dl=0).

**Comment by rneher** [comment] 2021-02-19 13:36
strange. I get ~200 excluded ones when running this on all 500k -- and those mostly have big indels. I'll investigate. You are running on Mac?

**Comment by andersonbrito** [comment] 2021-02-19 13:51
Yes. macOS 10.14, running nextalign `0.1.6`.

**Comment by rneher** [comment] 2021-02-19 17:42
This was due to large gaps in the sequences (due to stripping undertermined sites prior to alignment). 

Closing this now, but we'll document this.

**Closed by rneher** 2021-02-19 17:42 UTC
