### ISSUE TITLE
Import CSV/JSON

### ISSUE THREAD

**Issue by chaoran-chen** [nextstrain/nextclade#363] opened 2021-02-25 10:22 UTC
Hi Nextclade team. Since the Nextclade visualization, especially with the integrated tree view, is obviously extremely nice but the processing of a fasta file can take some time, I was wondering what you think about an import function. I often have the situation that I want to look at the same dataset repeatedly and it would be great if I could download the CSV/JSON the first time and just reuse it again. Or, for example, compute the CSV with the CLI tool and multithreading and to use the browser only for displaying.

**Comment by rneher** [comment] 2021-02-25 15:49
This is a good idea! 

We are hoping to make the tool quite a bit faster soon. 

two thoughts though:
 1) Chrome is a lot faster than firefox in my hands. 
 2) I think the cli can dump am auspice json which you can then visualize in auspice.us

**Comment by ivan-aksamentov** [comment] 2021-02-26 10:33
Duplicate of #211 

Some time ago I started a PR #282 to implement it, but there were some obstacles (and I no longer remember what they were :( )

Contributions are very welcome!

**Closed by ivan-aksamentov** 2021-02-26 10:33 UTC
Labels: good first issue, help wanted, t:feat
