### ISSUE TITLE
BUG: Out of bounds memory access (evaluating 'd.get(t)(e,r,n)') on M1 Safari only (not on Chrome)

### ISSUE THREAD

**Issue by elginakin** [nextstrain/nextclade#779] opened 2022-05-09 12:35 UTC
Hello. When attempting to run an Influenza B assembly and workflow through nextclade, my job fails continuously and I am met with the following message ``` Out of bounds memory access (evaluating 'd.get(t)(e,r,n)') ```. Moreover, this error occurs with any example workflow I have tried to run. Not sure what to make of it. Any help would be appreciated. Thanks. 

![Screen Shot 2022-05-09 at 8 30 48 AM](https://user-images.githubusercontent.com/63241361/167410680-ac594fa3-f28e-457e-8e3f-cfe5e450e6ca.png)

**Comment by corneliusroemer** [comment] 2022-05-14 12:26
Just reproduced this on Chrome and Safari on an iPhone 13, iOS 15.4.1

Noteworthily, on Chrome as well, not just Safari.

But sure, mobile isn't our focus.

**Comment by ivan-aksamentov** [comment] 2022-05-14 13:02
All browsers on iOS, including Chrome, use WebKit engine, because Apple requires so. So they all are just Safari with different skins.

**Comment by corneliusroemer** [comment] 2022-05-14 14:57
Aha, that explains it!

**Comment by ivan-aksamentov** [comment] 2022-06-09 10:12
@eakin1 If time allows, could you please try to reproduce this issue again with the new Nextclade version 2.0?

It looks roughly the same, but the internals are completely rewritten. We haven't released it yet, but here is a testing version:
https://master.clades.nextstrain.org/

We are trying to catch last bugs before the release, so your help is highly appreciated!

**Comment by ivan-aksamentov** [comment] 2022-06-09 14:11
Wow! New error... That is unexpected. Thank you for checking!

**Comment by ivan-aksamentov** [comment] 2022-06-09 14:14
Oh no! Looks like Safari does not support nested WebWorkers, which we need for v2.

> Safari unfortunately as of now does not support spawning Web Workers from inside other Web Workers.
https://stackoverflow.com/a/65099653

It's been 7 years and Apple doesn't seem to be particularly interested:
https://bugs.webkit.org/show_bug.cgi?id=25212

**Comment by ivan-aksamentov** [comment] 2022-06-16 18:48
The original issue is fixed in Nextclade v2 and regarding Safari - we decided to drop supporting it due to lack of required browser technologies in it and lack of technical resources on our side.

I added a warning message to notify users of unsupported browsers in https://github.com/nextstrain/nextclade/pull/866

If someone decides to fix Safari - contributions are welcome.

**Closed** 2022-06-16 18:48 UTC
Labels: t:bug, package: nextclade_wasm, prio: low, os: macOS
