### ISSUE TITLE
Some alignment strangeness

### ISSUE THREAD

**Issue by SeanSierra-Patev** [nextstrain/nextclade#842] opened 2022-06-08 17:40 UTC
Hello, I've tracked down some strange "insertions" and found they are the result of some strange decisions by the aligner. Pictured is the alignment as output by nextclade CLI
![wonky](https://user-images.githubusercontent.com/106685935/172681676-4dc9ca00-ac6a-4476-b46e-7aab97482949.PNG)

and then here I've just ammended the alignment manually (I get the same results using mafft) 
![unwonky](https://user-images.githubusercontent.com/106685935/172681813-d0ded77d-2db0-4381-a730-8138895e730a.PNG)

its not in a taxonomically informative region so the repercussions don't seem to extend beyond a little red flag when reviewing the report, but still worth mentioning I thought. This appears in the latest version of the CLI and the tool built into the illumina basespace DRAGEN workspace

**Comment by dbtara** [comment] 2022-06-08 19:47
Does Wuhan have TAC in the position where this was aligned?

**Comment by SeanSierra-Patev** [comment] 2022-06-08 20:11
Yep its there. Wuhan is bottom track in this figur
![wonky3](https://user-images.githubusercontent.com/106685935/172708064-5ca0019f-3d82-49ef-afca-1d2a2b02ab22.PNG)
e

**Comment by dbtara** [comment] 2022-06-08 20:19
I think that is the root cause, NextAlign uses Wuhan to anchor and somehow this one sequence got aligned weirdly due to that extra gap at end.

**Comment by dbtara** [comment] 2022-06-08 20:20
although the way it was aligned should be more costly as it has many gap extensions and mismatches

**Comment by corneliusroemer** [comment] 2022-06-08 21:51
Thanks for reporting!

This issue is a duplicate of https://github.com/nextstrain/nextclade/issues/746 

It is caused by too short terminal bandwidth.

It will be solved in version 2, which you can already use on the web for example.

**Closed** 2022-06-08 21:51 UTC
Labels: t:bug, duplicate, package: nextalign, v2

**Comment by SeanSierra-Patev** [comment] 2022-06-09 13:12
@ivan-aksamentov 
Thank you so much, the alignment was much improved in the online v2 alpha. I'll install the CLI alpha as well and give it some use with upcoming analyses. When I get weird stuff out of DRAGEN going forward I'll double check in the alpha CLI.



Really appreciate the help!

and @corneliusroemer 
 Thanks for closing it out, looking forward to v2 full release!
