### ISSUE TITLE
Possible misalignment Delta variant Nextclade version 1.7.4

### ISSUE THREAD

**Issue by VilenneFrederique** [nextstrain/nextclade#620] opened 2021-11-26 14:22 UTC
Dear,

A possible misalignment was observed in Nextclade version 1.7.4 with a Delta COVID19 sample.
Nextclade created the following gaps and insertions during the whole genome alignment:

![image](https://user-images.githubusercontent.com/80695537/143593114-eff20dd9-5710-4296-bddb-54505f3337d3.png)
![image](https://user-images.githubusercontent.com/80695537/143593466-8135d79b-2b04-40ad-9208-e9a84263082e.png)

When looking towards the actual sequence on IGV with a Wuhan reference genome:

![image](https://user-images.githubusercontent.com/80695537/143594242-030eb3e0-2690-4274-8885-f9978eacbd23.png)

An actual gap is observed.
Could this be a potential bug within Nextclade version 1.7.4?

Thank you in advance!

With kind regards,
Frédérique

**Comment by corneliusroemer** [comment] 2021-11-26 15:11
Dear @VilenneFrederique, thanks for your report. I'm happy to investigate. Could you please share the strain name of the offending sequence? Otherwise, there's not much I can do.

**Comment by corneliusroemer** [comment] 2021-12-01 00:28
I will close this issue since it cannot be worked on without further information.

If you provide the sequence names, I will reopen @VilenneFrederique

**Comment by VilenneFrederique** [comment] 2021-12-01 07:55
Dear,

Apologies for the late answer, things have been quite busy here regarding Covid.
I have provided the FASTA of the sample.
I think that will provide you with all information regarding the sample.
If you need anything else, please feel free to ask!
Thank you in advance!

With kind regards,
Frédérique
________________________________
Van: Cornelius Roemer ***@***.***>
Verzonden: woensdag 1 december 2021 1:28
Aan: nextstrain/nextclade ***@***.***>
CC: VilenneFrederique ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [nextstrain/nextclade] Possible misalignment Delta variant Nextclade version 1.7.4 (Issue #620)


I will close this issue since it cannot be worked on without further information.

If you provide the sequence names, I will reopen @VilenneFrederique<https://github.com/VilenneFrederique>

**Comment by corneliusroemer** [comment] 2021-12-01 17:47
Hi @VilenneFrederique, I can't find the FASTA file, did you attach it to the email? If so, that may not have worked.
Maybe drop it to something like https://pastebin.com/ if it's publicly shareable, otherwise you can tell me the name of the sequence and I'll fetch it myself from GISAID.

**Comment by VilenneFrederique** [comment] 2021-12-02 14:55
Dear Cornelius,

I've created the following pastebin:
Link: https://pastebin.com/ufTMCzmv
Name: Nextclade issue 620 fasta
Password: X7CSUftshu
Let me know if it works out!
With kind regards,

Frédérique

________________________________
Van: Cornelius Roemer ***@***.***>
Verzonden: woensdag 1 december 2021 18:47
Aan: nextstrain/nextclade ***@***.***>
CC: VilenneFrederique ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [nextstrain/nextclade] Possible misalignment Delta variant Nextclade version 1.7.4 (Issue #620)


Hi @VilenneFrederique<https://github.com/VilenneFrederique>, I can't find the FASTA file, did you attach it to the email? If so, that may not have worked.
Maybe drop it to something like https://pastebin.com/ if it's publicly shareable, otherwise you can tell me the name of the sequence and I'll fetch it myself from GISAID.

**Comment by corneliusroemer** [comment] 2021-12-02 22:25
Thanks for sharing the sequence. I had a look at the alignment produced by Nextalign.

In my view, the last 300bp of this sequence are of so low quality that Nextalign struggles to align. From 29740 onwards it seems almost unalignable.

Nextalign assumes that sequences do not have too many mutations and indels. In the end of your sequence, it's just too much.

So I don't think this is a bug as such, it looks like expected behaviour for a bad quality sequence.

**Closed by corneliusroemer** 2021-12-02 22:25 UTC
Labels: t:bug, needs triage, needs information
