### ISSUE TITLE
configuring qc.json file to avoid frameshift warning feature

### ISSUE THREAD

**Issue by jpflorido** [nextstrain/nextclade#469] opened 2021-06-29 12:35 UTC
Hi there,
Not sure whether this is a bug or it corresponds to the normal behavior of nextclade, but when setting `frameShifts.enabled` to _false_ in qc.json file, the check result is not considered 'bad', which is OK. However, still not able to visualize AA changes in the protein that has such frameshift(s)

Is there a way to avoid this new QC and show AA changes like in previous releases (<1.0.0)?
Thanks,
Javier

**Comment by rneher** [comment] 2021-06-30 15:14
Thanks for raising this! We are discussing how to handle this situation. 

If the frameshift appears close to the end the problem is not so bad. If it is early, it will result in a very large number of changes. Similarly, we are debating whether we should translate through a premature stop. If the stop is a sequencing error, amino acid changes past the stop might be of interest, but that would hide a potential truncation.

**Comment by jpflorido** [comment] 2021-07-05 15:35
Thanks for considering this issue.
Today, we came up with a couple of examples that might help to the discussion. We have analyzed two consensus genomes with the latest version of Nextclade. These two samples have very good quality (very high coverage value and uniformly distributed throughout the whole genome) and both of them belong to the Alpha lineage. All nextclade QC labels are green for these samples, but frameshift fails for one of them affecting gene S (and therefore no AA changes are reported for that gene). 

By reviewing carefully the whole procedure for generating consensus genome for these two samples, we identified the mutation that is causing the frameshift in the sample after aligning both of them to the reference genome using blast:
- For the good sample, there are a couple of deletions in gene S: one affecting two codons (the very well known H69-,V70-) and another affecting a single codon (Y144-). For the latter, the indel appears as --- in the blast alignment, which is OK (for the other indel, ------ appears, which is also OK)
- For the sample with the frameshift flag, the H69-,V70- is detected, but instead of having Y144- (which is common for Alpha lineage) , it has Y144X. Having a look to the alignment of consensus genome against the reference genome, the following alignment appears for that position: N--

For the latter case, the consensus genome (which has been built using iVar), includes a N instead of - . So, for that codon, there is a N-- . The indel is clearly there when visualizing BAM file (it is very well supported but for the first nucleotide is indeed slightly below the frequency threshold). So, after gap stripping the length of S gene is not a multiple of 3.

A couple of suggestions can be discussed here:

- Is it reasonable a different interpretation of indels when Ns are present? That is, assume that N-- is really --- ? 
- Is it possible the same behaviour as previous Nextclade release (< v1.1.0)? That is, to show the whole list of mutations despite of frameshifts mutations or at least, when the indel that causes the frameshift flag has a N around the deletion position.

Thanks,
Javier

**Comment by rneher** [comment] 2021-07-09 12:25
Thanks for the example. it seems that Nextclade is working as intended, but not necessarily in the way that is most useful. 

With `N--`, iVar seems to be saying: "there is a nucleotide at pos 1, but I don't know which one. positions 2 and 3 are deleted." If this was a correct, the protein would be frame shifted.  This should be improved in iVar.

We could consider filling gaps with `N` in a frame shifted sequence and translating as before. But this would need to come with a big frame shift warning, because the sequence clearly has a problem...

Anyway, thanks for raising this. This will require some more thoughts and development effort.

**Comment by fortuno** [comment] 2021-09-03 12:06
Hi there,

I just found this interesting thread. I just wanted to know if nextclade is planning to include an option to treat this scenario differently (maybe as it was treated before). I mean, warning users about a potential frameshit that can break the rest of the protein sounds good to me but I would prefer to keep the remaining found variants after that frameshit instead of remove them all. 

Sometimes the potential frameshit can be produced by low quality regions which could produce "false frameshits". I found the example from @jpflorido very illustrative: If a well-known deletion (H69*) is incomplete because one low quality nucleotide (codon would be "N--"), that is more likely to be a deletion (where one nucleotide is N because of its low quality) rather than a frameshit. I understand that nextclade should warn about a potential frameshit there but, at least, I would prefer to have an option to allow users report the remaining variants so they can decide.

What do you think? Thanks in advance for your help!

**Comment by ivan-aksamentov** [comment] 2021-09-03 12:41
Hi @fortuno ,

I am working on the algorithm in https://github.com/nextstrain/nextclade/pull/533 and we are still discussing, so no promises.

There are some challenges - algorithmic, in user interface and that different people want to see different things. So ideas and feedback are always helpful, thanks.

**Comment by ivan-aksamentov** [comment] 2021-09-30 12:33
Nextclade CLI 1.4.0 and Nextclade 1.7.0 no longer ignores genes with frame shifts. See [changelog](https://github.com/nextstrain/nextclade/blob/release/CHANGELOG.md#nextclade-web-170-nextclade-cli-140-nextalign-cli-140-2021-09-30) for more context.

I am closing this issue, but don't hesitate to open a new issue if problems or questions remain.

**Closed by ivan-aksamentov** 2021-09-30 12:33 UTC
Labels: t:bug, t:feat, t:talk, package: nextclade
