### ISSUE TITLE
cli genemap input issue

### ISSUE THREAD

**Issue by mcnaber** [nextstrain/nextclade#488] opened 2021-08-04 19:17 UTC
Hello! 

I have tried to run the genemap example input command for the command line interface (--input-gene-map=genemap.gff) using the example genemap provided. However, I received the following error: "SyntaxError: genemap.gff: Unexpected token # in JSON at position 0". 

It seems to want a .json file format, but when I looked into the --help page and used the .json file provided there, I recieved this message "ErrorGeneInvalidRange: GeneMap: in gene "genome_annotations": expected gene length to be divisible by 3, but got NaN". 

The program works properly when I don't try to input a genemap, but I would like to use this feature. Anyone else run into issues or have tips? 

Thank you.

**Comment by ivan-aksamentov** [comment] 2021-08-04 19:32
Hi @mcnaber,

What version and what tool (nextclade, Nextalign) are you using?

It might be internal issue (a bug) or something wrong with your genemap file.

In order for me to reproduce the issue, could you attach or paste the contents of your `genemap.gff` file?

If possible, provide the fill command line invocation and other input files you use. If these files are private, you can send find my email address here:
https://www.biozentrum.unibas.ch/research/researchgroups/group/unit/neher/

**Comment by mcnaber** [comment] 2021-08-04 19:48
Thank you! 

I am trying to use the nextclade tool for SARS-COV-2 analysis. Here are the contents for the .gff file in .txt file form: 
[genemap.txt](https://github.com/nextstrain/nextclade/files/6933981/genemap.txt)

Here is where I directly copied the contents from. This is also where I pulled the 'sequences.fasta' file to use as the input data: https://github.com/nextstrain/nextclade/tree/master/data/sars-cov-2

Here is the command I am attempting to run: 
nextclade  --input-fasta=sequences.fasta  --input-gene-map=genemap.gff --output-json=outputnextclade.json

When I tried the .json format, this is the where I copied the contents from as it was linked in the nextclade --help: https://github.com/nextstrain/nextclade/blob/20a9fda5b8046ce26669de2023770790c650daae/packages/web/src/algorithms/defaults/sars-cov-2/geneMap.json

This is the full error message I receive when I run the command: 
SyntaxError: genemap.gff: Unexpected token # in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object._readFile (/usr/local/lib/node_modules/@neherlab/nextclade/dist/nextclade.js:604:612)

Thank you for your help!

**Comment by mcnaber** [comment] 2021-08-04 19:51
When I run the following command using the .json file for the genemap: nextclade  --input-fasta=sequences.fasta  --input-gene-map=genemap.json --output-json=outputnextclade.json

This is the error that I recieve: 
ErrorGeneInvalidRange: GeneMap: in gene "genome_annotations": expected gene length to be divisible by 3, but got NaN
    at /usr/local/lib/node_modules/@neherlab/nextclade/dist/nextclade.js:1485:7345
    at Array.map (<anonymous>)
    at convertGeneMap (/usr/local/lib/node_modules/@neherlab/nextclade/dist/nextclade.js:1485:6659)
    at _callee5$ (/usr/local/lib/node_modules/@neherlab/nextclade/dist/nextclade.js:12:19017)
    at tryCatch (/usr/local/lib/node_modules/@neherlab/nextclade/dist/nextclade.js:419:1007)
    at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/@neherlab/nextclade/dist/nextclade.js:419:4958)
    at Generator.next (/usr/local/lib/node_modules/@neherlab/nextclade/dist/nextclade.js:419:2146)
    at asyncGeneratorStep (/usr/local/lib/node_modules/@neherlab/nextclade/dist/nextclade.js:424:275)
    at _next (/usr/local/lib/node_modules/@neherlab/nextclade/dist/nextclade.js:424:586)

**Comment by ivan-aksamentov** [comment] 2021-08-04 20:02
@mcnaber Looks like you are using Nextclade version 0.x, which is the old, JavaScript implementation, is long obsolete and not maintained now.

Where did you find out about it? I would like to add a note there that this version is no longer recommended.

I recommend you to try Nextclade version 1.x
https://github.com/nextstrain/nextclade/releases

It has a few differences though. Notably, you need to specify all the input files explicitly (it does not include any default data).

The files that are currently in the [data/]https://github.com/nextstrain/nextclade/tree/master/data) directory are only suited for Nextclade 1.x. If you insist on using Nextclade 0.x, you will need to get the data from the older git tags.

**Comment by mcnaber** [comment] 2021-08-05 16:37
Thank you for noticing that. 

I used docker to install it the first time I followed the instructions here: https://hub.docker.com/r/nextstrain/nextclade . This is the command I used: npm install --global @neherlab/nextclade 

It seems when I try to install the global version, it installs the version 0.x. Is the version 1.x no longer a global version of the program? I now have nextclade operating properly with version 1.x, but it is a local version. Thanks again!

**Comment by ivan-aksamentov** [comment] 2021-08-05 16:49
Looks like our DockerHub page is in a bit of a neglected state. Tanks for pointing me to it. We will try to change it.

> Is the version 1.x no longer a global version of the program?

There is no global or local version. 

We shipped Nextclade 0.x on NPM, because it's where JavaScript packages are usually distributed. But now Nextclade is rewritten in C++, for speed, so NPM makes little sense. We no longer ship Nextclade on NPM, so you can only obtain the old version.

Nextclade 1.x is a self-contained executable. You can simply download it and run it directly. It's convenient to put it into a directory that is included into system `$PATH`, so that it's always available on command line, no matter where you are.

Also Nextclade 1.x no longer needs Node.js or NPM, so if you don't need them they can be removed.

> I now have nextclade operating properly with version 1.x, but it is a local version. Thanks again!
I will close the issue then. But if there are more problems or questions, don't hesitate to comment here or to open another issue.

**Closed by ivan-aksamentov** 2021-08-05 16:49 UTC
Labels: t:bug
